Rebind pug_html instead of using an arg of the same name
austindebruyn/pug-plugin-try-catch pull request #2
Opened 2017-04-30 21:55 UTC by myfreeweb

The `function(pug_html)` approach did not work with mixins, since mixins are functions that reference the original pug_html variable from the beginning of template code! Mixins simply returned no output.

This probably needs more testing but seems to work for me.

2017-04-30 22:03 UTC, austindebruyn requested changes
hey thanks for the fix - looks like it should work. The tests all pass, but there's a linting error. I don't use pug mixins so I haven't run into this issue, but I should get some time soon to take a look and get this merged. hopefully we can get a test case in there that simulates mixin usage

2017-04-30 22:03 UTC, austindebruyn commented on lib/parse.js
> +    Object.assign({}, codeBlockDefaults, { val: '; real_pug_html += pug_html; }; pug_html = real_pug_html; }).bind(this)()' }),
I'd prefer a `.call(this)` instead of `.bind(this)()`.

2017-04-30 22:25 UTC, myfreeweb commented
Added a test with actual mixin usage.

2017-05-01 02:28 UTC, austindebruyn approved these changes

2017-05-01 02:29 UTC, austindebruyn commented
The linting error was actually my fault - master wasn't passing. thanks for the fix :+1:

2017-05-01 02:29 UTC, merged

2017-05-01 02:32 UTC, austindebruyn commented
went out as ` pug-plugin-try-catch@1.2.0`